### ISSUE TITLE
如何对插件进行多语言适配？

### ISSUE THREAD

**Issue by dz-paji** [g-plane/blessing-skin-plugin-docs#1]
并没有看到插件多语言的文案 感觉在主程序是英文的情况下 混进几个中文字眼有些别扭

**Comment by dz-paji** [comment]
顺便 在线阅读的link 404了

**Comment by g-plane** [comment]
有的：https://github.com/bs-community/blessing-skin-plugin-docs/blob/master/docs/i18n.md

**Comment by dz-paji** [comment]
哦豁 谢谢

**Comment by g-plane** [comment]
地址已更新：https://bs-community.github.io/blessing-skin-plugin-docs/
